### ISSUE TITLE
úkol 7. lekce

### ISSUE THREAD

**Issue by AjaSimak** [AjaSimak/python-032021#1]
Ahoj @pesikj, posílám 7. úkol https://github.com/AjaSimak/python-032021/blob/cf294d9e53c056e5b0072253bf42180b919abbe4/%C3%BAkoly/7.%20ukol.py. Díky za komentáře. A.

**Comment by pesikj** [comment]
Ahoj Andreo, super. Líbily se mi i pokusy :-) Pro poslední pokus je potřeba odebrat rybu s nulovou hmotností:
`ryby = ryby[ryby["Weight"] > 0]`
Obecně je to asi chyba v datech, takže bys to klidně mohla vyfiltrovat pro celou analýzu, ale projeví se to až zde.
J.
