### ISSUE TITLE
úkol 8. lekce

### ISSUE THREAD

**Issue by AjaSimak** [AjaSimak/python-032021#2]
Ahoj @pesikj, posílám úkol 8. lekce, díky za komentáře. A.

https://github.com/AjaSimak/python-032021/blob/90298bdab943a71c816214db2084b4607ba3ae53/%C3%BAkoly/8.%20ukol_csco.py

https://github.com/AjaSimak/python-032021/blob/90298bdab943a71c816214db2084b4607ba3ae53/%C3%BAkoly/8.%20ukol_python.py

**Comment by pesikj** [comment]
Ahoj Andreo,
super :-)
J.
